### ISSUE TITLE
Build fails on CentOS 7

### ISSUE THREAD

**Issue by kripper** [rcouch/rcouch#23] opened 2015-01-10 22:14 UTC
This is the output:

[root@localhost rcouch-rcouch-1.0.1]# make
==> couch-1.6.1 (get-deps)
==> couch_mrview-0.1 (get-deps)
==> couch_replicator-0.1 (get-deps)
==> couch_rel (get-deps)
==> rel (get-deps)
==> rcouch-rcouch-1.0.1 (get-deps)
ERROR: Dependency dir /usr/lib64/erlang/lib/couch_index-0.1 failed application validation with reason:
{missing_app_file,"/usr/lib64/erlang/lib/couch_index-0.1"}.
ERROR: 'get-deps' failed while processing /root/src/rcouch/rcouch-rcouch-1.0.1: rebar_abort
make: *** [deps] Error 1

**Comment by kripper** [comment] 2015-01-10 22:27
Solved by uninstalling couchdb RPM.

**Comment by benoitc** [comment] 2015-01-10 22:29
Was just looking at it. Thanks for the feedback! btw you should use thee 1.0.2 witch is the latest stable :)

**Comment by kripper** [comment] 2015-01-10 22:46
Got a missing lib (it is defined in libdl.so.2):

/usr/bin/ld: /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/nsprpub/lib/libnspr4.a(prmem.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
ERROR: cc c_src/couch_js/http.o c_src/couch_js/main.o c_src/couch_js/utf8.o c_src/couch_js/util.o  /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/js/lib/libjs_static.a /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/nsprpub/lib/libnspr4.a -lcurl -lstdc++ /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/js/lib/libjs_static.a /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/nsprpub/lib/libnspr4.a -lcurl -lstdc++ -lpthread -lm  -L/usr/lib64/erlang/lib/erl_interface-3.7.15/lib -lerl_interface -lei -o priv/couchjs failed with error: 1 and output:
/usr/bin/ld: /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch/.libs/nsprpub/lib/libnspr4.a(prmem.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /root/src/rcouch/rcouch-rcouch-1.0.2/src/couch: rebar_abort
make: *** [compile] Error 1

**Comment by kripper** [comment] 2015-01-10 22:50
"-ldl" must be added somewhere.

**Comment by kripper** [comment] 2015-01-10 22:55
make and make rel worked fine now, but there is no "make package" rule?

**Comment by kripper** [comment] 2015-01-26 19:14
Ok, on latest github version, "make package" is now defined but generates the following error:

Cloning into 'ssl_verify_hostname'...
==> idna (get-deps)
==> ssl_verify_hostname (get-deps)
==> couch_replicator (get-deps)
==> couch_dbupdates (get-deps)
==> couch_randomdoc (get-deps)
==> geocouch (get-deps)
==> node_package (get-deps)
make[1]: Leaving directory `/root/src/rcouch/rcouch/distdir/rcouch-clone'
cd distdir/rcouch-clone && git archive --format=tar --prefix=rcouch-1.0.4pre/ HEAD | (cd .. && tar xf -) && cp dependency_manifest.git ../rcouch-1.0.4pre/ && mkdir ../rcouch-1.0.4pre/deps && for dep in deps/*; do cd ${dep} && git archive --format=tar --prefix=${dep}/ HEAD | (cd ../../../rcouch-1.0.4pre && tar xf -) && mkdir -p ../../../rcouch-1.0.4pre/${dep}/priv && printf "`git describe --long --tags 2>/dev/null || git rev-parse HEAD`" > ../../../rcouch-1.0.4pre/${dep}/priv/vsn.git && cd ../..; done
tar -C distdir -czf distdir/rcouch-1.0.4pre.tar.gz rcouch-1.0.4pre
ln -s distdir package
make -C package -f rcouch-1.0.4pre/deps/node_package/Makefile
make[1]: Entering directory `/root/src/rcouch/rcouch/distdir'
echo "{app_version, \"1.0.4pre\"}." >> rcouch-1.0.4pre/deps/node_package/priv/templates/rpm/vars.config
make -f rcouch-1.0.4pre/deps/node_package/priv/templates/rpm/Makefile.bootstrap
make[2]: Entering directory `/root/src/rcouch/rcouch/distdir'
/usr/bin/rebar -v create \
                    template_dir=rcouch-1.0.4pre/deps/node_package/priv/templates \
                    template_vars=rcouch-1.0.4pre/pkg.vars.config template=rpm
==> distdir (create)
Writing Makefile
ERROR: create failed while processing /root/src/rcouch/rcouch/distdir: {template,[66,97,100,32,99,111,110,116,101,120,116,32,102,111,114,32,
           "package_commands",58,32,
           [123,
            ["list",44,10,
             ["  ","  ",
              [32,[["  ",32,32],"  ",32,32],["  ",32,32],"  ",32,32],
              32,
              [["  ",32,32],"  ",32,32],
              ["  ",32,32],
              "  ",32,32],
             [91,
              [[91,[[123,["name",44,"\"rcouch\""],125]],93],
               44,
               [91,[[123,["name",44,"\"couchjs\""],125]],93]],
              93]],
            125]]}
make[2]: *** [bootstrap] Error 1
make[2]: Leaving directory `/root/src/rcouch/rcouch/distdir'
make[1]: *** [ostype] Error 2
make[1]: Leaving directory `/root/src/rcouch/rcouch/distdir'
make: *** [package] Error 2

**Comment by benoitc** [comment] 2015-01-27 00:01
Thanks for the feedback. 

I fixed the couchdb-couch applications to build couchjs on CENTOS:
https://github.com/rcouch/couchdb-couch/commit/dce95b42d5150734925760389199a65f45938e53

However I can't reproduce the last issue you mention. Once the error above is fixed I can build rcouch. You can find an rpm of the 1.0.4 preview here:
https://drive.google.com/open?id=0B2gNkR7hgkIRWmVzNGlhSWtMQms

All the rpm files are here:
https://drive.google.com/folderview?id=0B2gNkR7hgkIRdExLaDhQc3JjVE0&usp=sharing

Let me know if it works for you!

**Comment by kripper** [comment] 2015-01-27 00:27
Hi Benoit:

Ok. The RPM works.
Now I'm missing futon.
Where is it?
It's not on /_utils at least.

**Comment by benoitc** [comment] 2015-01-27 08:09
Right, the path in the configuration is not correct. I am fixing that right now.

**Comment by benoitc** [comment] 2015-02-07 07:24
fixed in latest master.

**Closed by benoitc** 2015-02-07 07:24 UTC
